### ISSUE TITLE
How to install this on a Mac?

### ISSUE THREAD

**Issue by andupotorac** [chflame163/ComfyUI_FaceSimilarity#5]
I did install the dlib libarary in my ComyUI environment for a similar node - [Face Analysis](https://github.com/cubiq/ComfyUI_FaceAnalysis). There in the Custom Node it had a folder where it asked me to place the following 4 data files, and it works.
<img width="715" alt="Screenshot 2024-08-15 at 16 01 50" src="https://github.com/user-attachments/assets/b9ddd752-97da-46bc-8aff-737b75c54628">

Can I point to that folder somehow if you're using those resources too, or what do you suggest I do so that your node works on a Mac? I want to compare the two nodes and see if I get similar results.

**Comment by andupotorac** [comment]
This is the error I get now, so I assume I need to connect these to the Node somehow.
<img width="1053" alt="Screenshot 2024-08-15 at 16 14 30" src="https://github.com/user-attachments/assets/dd6b5db3-62ee-4098-922c-d04d83427021">

**Comment by chflame163** [comment]
I found [this document](https://gist.github.com/ageitgey/629d75c1baac34dfa5ca2a1928a7aeaf),  see if it is helpful. Sorry, I don't have any Mac device to test it :）

**Comment by andupotorac** [comment]
I have it installed, it workes with the other node, but not with this one. So my question was if I have to move / copy the data files somewhere for your node to access them. Where does it look for them?

**Comment by andupotorac** [comment]
Idk, it didn't work when I placed the dlib models there. I'll close it up.
